# Changelog configuration
#
# For more information: https://towncrier.readthedocs.io/en/latest/configuration.html
#

[tool.towncrier]
package = "sample"  # Name of the project
directory = ".changes"  # Directory of the news fragments
filename = "CHANGELOG.md"  # File which holds the CHANGELOG or news files.


# News types (order of appearance in CHANGELOG) ###############################x
# Whenever a news fragement is generated, the full CHANGELOG will be generated
# according to the ordering listed below.
#

[[tool.towncrier.type]]
directory = "security"
name = "Security"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "fix"
name = "Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "bug"
name = "Bugs"
showcontent = true

[[tool.towncrier.type]]
directory = "chore"
name = "Chores"
showcontent = true
