name: Release Helm Charts
run-name: ${{ github.actor }} is updating the Helm repository

on:
  workflow_dispatch:
    inputs:
      release_all:
        type: boolean
        description: "Republish all charts?"
        default: false
  push:
    branches:
    - main
    paths:
    - repo/**

jobs:
    release:
        runs-on: ubuntu-latest

        steps:

        - name: 'Git Checkout'
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: 'Configure & Install Helm'
          uses: azure/setup-helm@v3

        - name: 'Push modified Helm packages to the container registry'
          if: "${{ github.event.inputs.release_all == 'false' }}"
          env:
            HELM_EXPERIMENTAL_OCI: '1'
          run: |
            git diff --name-only -r HEAD^1 HEAD | grep .tgz | while read line || [[ -n $line ]];
            do
                helm push $line oci://TODO
            done

        - name: 'Push all Helm charts to the container registry'
          if: "${{ github.event.inputs.release_all != 'false' }}"
          env:
            HELM_EXPERIMENTAL_OCI: '1'
          run: |
            ls repo | grep .tgz | while read line || [[ -n $line ]];
            do
                helm push repo/$line oci://TODO
            done